#!/bin/bash

folder=$(dirname $1)
name=${1::-4}
image=$1

mv /home/$USER/.Xdefaults /home/$USER/.Xdefaults.bak
head -n 9 .Xdefaults.bak > .Xdefaults

cont=0
for i in $(colors -en 16 $image)
do
  cont=$(( cont + 1 ))
  case $cont in
    2)
      background=$(echo $i | tr -d '#')
      ;;
    7)
      neutral=$(echo $i | tr -d '#' )
      ;;
    15)
      foreground=$(echo $i | tr -d '#')
      ;;
  esac
  printf "*color%d:%s\n" $cont $i >> /home/$USER/.Xdefaults
done

printf "\n*background:#%s" $background >> /home/$USER/.Xdefaults
printf "\n*foreground:#%s" $foreground >> /home/$USER/.Xdefaults
rm /home/$USER/.colors
printf "BACKGROUND #FF%s\n" $background >> /home/$USER/.colors
printf "FOREGROUND #FF%s\n" $foreground >> /home/$USER/.colors
printf "NEUTRAL #FF%s\n" $neutral >> /home/$USER/.colors

feh --bg-fill $image
cp $image "$folder/wp.png"
